# Copyright 2018, 2019 Peter Dimov
# Distributed under the Boost Software License, Version 1.0.

language: cpp
sudo: false

env:
  - REPO=assert
  - REPO=bind
  - REPO=boostdep
  - REPO=boost_install
  - REPO=check_build
  - REPO=cmake
  - REPO=core
  - REPO=describe
  - REPO=endian
  - REPO=function
  - REPO=headers
  - REPO=lambda2
  - REPO=mincmake
  - REPO=mp11
  - REPO=smart_ptr
  - REPO=system
  - REPO=throw_exception
  - REPO=timer
  - REPO=variant2

script:
  - git clone https://github.com/boostorg/$REPO && git -C $REPO diff --exit-code origin/master origin/develop

notifications:
  email:
    on_success: always
