name: CI

on:
  pull_request:
  push:
    branches:
      - master
      - develop
      - feature/**
  schedule:
    - cron: '30 10 * * 0'

jobs:
  posix:
    strategy:
      fail-fast: false
      matrix:
        repo:
          - accumulators
          - array
          - assert
          - bimap
          - bind
          - chrono
          - compat
          - container_hash
          - core
          - crc
          - describe
          - endian
          - function
          - headers
          - iostreams
          - lambda
          - lambda2
          - mp11
          - msm
          - numeric_conversion
          - ptr_container
          - ratio
          - smart_ptr
          - system
          - thread
          - throw_exception
          - timer
          - tuple
          - type_erasure
          - typeof
          - uuid
          - variant2
          - boostdep
          - boost_install
          - check_build
          - cmake
          - quickbook

    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: Diff master..develop
        run: |
          git clone https://github.com/boostorg/${{matrix.repo}} && git -C ${{matrix.repo}} diff --exit-code origin/master origin/develop
